### ISSUE TITLE
Pillow, in place of PIL

### ISSUE THREAD

**Issue by notpratheek** [rupa/epub#11]
Thanks for this terminal epub reader ! :smile: 

Is it possible to change the image handling from PIL to Pillow ? 

(Since, upon looking around I found out that, PIL was dead, and the Pillow was considered to be its replacement)

**Comment by arpit1997** [comment]
Good suggestion @notpratheek [python Image library](https://pypi.python.org/pypi/PIL) is considerd to be dead for now it is not in active development.[PILLOW](https://pypi.python.org/pypi/Pillow/2.2.1) was  a good and active fork of PIL so it should be used. PIL has got many bugs now and there issue tracker is not active also.
:small_airplane: :smile_cat: :smiley_cat:

**Comment by rupa** [comment]
changed dep to Pillow. Now to actually use it well ...
